### ISSUE TITLE
Configure Prometheus

### ISSUE THREAD

**Issue by remingtonc** [cisco-ie/ez-dash#1]

**Comment by remingtonc** [comment]
@skkumaravel If there are any metrics you're thinking of that I should already configure Prometheus to scrape let me know what they are. Otherwise will look.

**Comment by skkumaravel** [comment]
Closed by #6?

**Comment by remingtonc** [comment]
Maybe? I have no idea. Does it totally work? None of the rules we have right now are real.

**Comment by remingtonc** [comment]
Not closing this because the configuration addresses some things that don't exist right now.

**Comment by skkumaravel** [comment]
Like what?

**Comment by remingtonc** [comment]
Take like this random rule I threw together, doesn't actually do anything. https://github.com/cisco-ie/ez-dash/blob/master/prometheus/rules.d/test.rule

Do we need rules?
